version: '1.0'

services:
  postgres:
    image: postgres:17
    container_name: cspaglu-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cspaglu-db
    ports:
      - "5134:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cspaglu-network

volumes:
  postgres_data:

networks:
  cspaglu-network:
    driver: bridge
