version: '3.8'

services:
  backend:
    build:
      context: ./apps/server
    container_name: cspaglu-server
    restart: always
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - cspaglu-network

networks:
  cspaglu-network:
    driver: bridge
