version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: cspaglu-server
    restart: always
    ports:
      - '8081:8081'                   
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - cspaglu-network

networks:
  cspaglu-network:
    driver: bridge
